kind = "web"
previewPath = "/"
title = "Mindvisi"
version = "1.0.0"
id = "artifacts/mindvisi"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24476

[services.development]
run = "pnpm --filter @workspace/mindvisi run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mindvisi", "run", "build" ]
publicDir = "artifacts/mindvisi/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24476"
BASE_PATH = "/"
